### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by shwoo1219** [chenhsuanlin/inverse-compositional-STN#10]
Hello,

Thanks for sharing the code of your interesting work IC-STN.

I am now using Pytorch version. However, I meet runtime error as below:

 Expected a Tensor of type Variable but found an undefined Tensor at position #2 for iterable argument #0 'tensors'

It seems there is an operation that includes tensor which should be defined as Variable.

Any comments?

Thanks.

**Comment by chenhsuanlin** [comment]
Could you please include a more detailed error message, specifically where the error happened? Thanks!

**Comment by jiangwei221** [comment]
I also met this problem.
I modified the 'mtrx2vec' and 'compose' fun in warp.py, it works now.
You can check my pull request.
