### ISSUE TITLE
How to use combination like IC-STN-->CNN-->IC-STN-->CNN type of structure

### ISSUE THREAD

**Issue by sumeetssaurav** [chenhsuanlin/inverse-compositional-STN#12]

**Comment by chenhsuanlin** [comment]
It should be straightforward -- you could possibly add a CNN on top of the final warped image from the first IC-STN, and the second IC-STN reads from the output of the CNN, and so on.
We didn't experiment with this as it wasn't really the central narrative of the paper, but if you happened to try it out, let me know what you find!
