### ISSUE TITLE
Why inputs of STN and ic-STN are different?

### ISSUE THREAD

**Issue by wintersurvival** [chenhsuanlin/inverse-compositional-STN#13]
Thank you for your sharing!
I am puzzled about the inputs of STN and ic-STN. The inputs of STN and ic-STN is different, does that fair?

**Comment by chenhsuanlin** [comment]
During evaluation, the input warp parameters of IC-STN would be 0 (identity transform), so initially it warps on the input image and is effectively the same as STN.
