### ISSUE TITLE
IC-STN algorithm for landmark detection

### ISSUE THREAD

**Issue by SunnyDp** [chenhsuanlin/inverse-compositional-STN#14]
Thanks for your great job. I want to use the IC-STN for the face landmark detection task. Different from the classification task, do I need to inverse transform the transformed image to obtain the points on the orginal 
image？Waiting for your advice.

**Comment by chenhsuanlin** [comment]
I'm not exactly sure what you mean, could you please elaborate?

**Comment by SunnyDp** [comment]
@chenhsuanlin Sorry for the unclear question. In the classification task such as MNIST, the transformed images are obtained to get more accurate result, but for regression task, such as face landmark detection, the aim is to get the point coordinates on the face. So if I use the IC-STN to transform the image and detect the points on the transformed image, the coordinates are not on the original image. How can I deal with it?
Is it necessary to inversely transform the coordinates?

**Comment by wuneng** [comment]
@SunnyDp  i have the same problem with you

**Comment by chenhsuanlin** [comment]
Yes, that sounds right to me -- as long as your warp function is invertible (e.g. affine or homography), you can simply invert the parameters from IC-STN and apply them on the facial landmarks. (cc'ing @wuneng also)
