### ISSUE TITLE
How to use this code to align source image to target image?

### ISSUE THREAD

**Issue by KakaVlasic** [chenhsuanlin/inverse-compositional-STN#17]
First, thanks for releasing a clean and well trained code for your paper!
I have two sets of image(source and target), and I want to align source image to the target image. Should I try to replace data "label" in dataloader to "target/template"? or what I should change?

**Comment by chenhsuanlin** [comment]
If you're only comparing pixel intensities like in the LK algorithm, you could just remove the classifier parts and use L1/L2 loss between your images (warped source vs. target).
If you're doing something fancier like feature losses, you could also modify the classifier to be shallower (and optionally freezing the weights during training, depending on what you want to achieve).
