### ISSUE TITLE
Support for RGB images?

### ISSUE THREAD

**Issue by xinghedyc** [chenhsuanlin/inverse-compositional-STN#3]
Thanks for sharing such great work, Does IC-STN support RGB images as inputs?

**Comment by chenhsuanlin** [comment]
Yes - if you want to modify from the existing code, the main steps are
1. change the shape of `imageRawBatch` to `[None,28,28,3]` in **train.py L58**
2. change the corresponding convolution kernel dimensions
3. comment out **data.py L85** (as `imageBatch` is already 4-D)
4. change the last dimension to 3 in **graph.py L81,83**

RGB inputs should work after these steps.
Let me know if you have other questions!

**Comment by xinghedyc** [comment]
@ericlin79119 Thanks a lot for your quick reply!
I'll try it.
