### ISSUE TITLE
Stuck at loading MNIST dataset

### ISSUE THREAD

**Issue by phongnhhn92** [chenhsuanlin/inverse-compositional-STN#5]
Hello guys, I tried to run train.py using this command 
`python train.py CNN --group groupCNN --model modelCNN --lr 0.001 --lr 0.001 --batchSize 32 --maxIter 2000 --warpType translation`
But somehow I stuck at this loading MNIST dataset. My Internet works normally so I dont know what is going on. I also dont know if the parameter I used on the command above is correct or not since the readme doesnt provide any examples to compare.
Thanks
![a](https://user-images.githubusercontent.com/11288381/28608320-e6836f06-721a-11e7-8eb8-1e838c4b0842.png)

**Comment by chenhsuanlin** [comment]
The command line works fine on my side. Could you double-check whether there are files downloaded to `data` and `MNIST_data`? The code should automatically download MNIST if doesn't exist in your directory.
