### ISSUE TITLE
PyTorch Implementation

### ISSUE THREAD

**Issue by FuriouslyCurious** [chenhsuanlin/inverse-compositional-STN#6]
Hi Eric,
    Are you aware of any PyTorch implementations of IC-STN?

Thanks!

**Comment by chenhsuanlin** [comment]
Not that I'm currently aware of, but I'd be most delighted to know one!

**Comment by FuriouslyCurious** [comment]
Cool - I will experiment and see if I can create one.

**Comment by chenhsuanlin** [comment]
@FuriouslyCurious I've now added a PyTorch implementation. Let me know if you still happen to find it useful and if you run into problems!

**Comment by FuriouslyCurious** [comment]
Thanks a lot Eric! I will try it out soon.
